### ISSUE TITLE
Suddenly not working

### ISSUE THREAD

**Issue by Swerda** [exelix11/dvr-patches#24]
Opened the GUI and for the first time it refuses to connect. On the latest versions of everything, and it was working the night before. I had not updated to system update 14.1 or its Atmosphere equivalent when I first got this error, but I have now and am still getting this error. I am posting this here instead of in the SysDVR page as I'm using this wirelessly for Smash Ult, but I can change it if need be.

Press F11 for full screen, esc to quit.

Initialized SDL with direct3d renderer
Terminating ReceiveFromDeviceThread for Audio due to System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(ValueTask task)
   at SysDVR.Client.Sources.TCPBridgeSource.WaitForConnection()
   at SysDVR.Client.StreamThread.DeviceThreadMain(CancellationToken token)
Terminating ReceiveFromDeviceThread for Video due to System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(ValueTask task)
   at SysDVR.Client.Sources.TCPBridgeSource.WaitForConnection()
   at SysDVR.Client.StreamThread.DeviceThreadMain(CancellationToken token)

**Comment by exelix11** [comment]
This is a connection problem and not related to dvr-patches.

The error is that it couldn't connect to the console, make sure sysdvr is running and in tcp bridge mode on the pc check that the IP address of the console is correct.

This error can happen sometimes while sysdvr resets the socket to resume from sleep mode, trying again works right away.
